cache:
  directories:
    - _build
    - deps
sudo: true
language: elixir
before_install:
  sudo apt-get -y install inotify-tools
elixir:
  - 1.7
  - 1.8
otp_release:
  - 19.1
  - 20.1
env: MIX_ENV=test
notifications:
  recipients:
    - roman.heinrich@gmail.com
